const ErrorCodes = Object.freeze({
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  ALREADY_BAPTIZED: 'ALREADY_BAPTIZED',
  MEMBER_NAME_EXISTS: 'MEMBER_NAME_EXISTS',
  SOUL_WIN_NAME_EXISTS: 'SOUL_WIN_NAME_EXISTS',
  INVALID_WINNER: 'INVALID_WINNER',
})

module.exports = ErrorCodes
