process.env.NODE_ENV ??= 'test'
process.env.DATABASE_URL ??= 'postgresql://user:pass@localhost:5432/test_db'
process.env.R2_ACCOUNT_ID ??= 'test-account-id'
process.env.R2_ACCESS_KEY_ID ??= 'test-access-key-id'
process.env.R2_SECRET_ACCESS_KEY ??= 'test-secret-access-key'
process.env.JWT_SECRET ??= 'test-jwt-secret'
process.env.APP_API_KEY ??= 'test-api-key'
process.env.FRONTEND_URL ??= 'http://localhost:3000'
