process.env.NODE_ENV ??= 'test'
process.env.DATABASE_URL ??= 'postgresql://user:pass@localhost:5432/test_db'
process.env.SUPABASE_URL ??= 'https://test.supabase.co'
process.env.JWT_SECRET ??= 'test-jwt-secret'
process.env.LBBC_API_KEY ??= 'test-api-key'
process.env.FRONTEND_URL ??= 'http://localhost:3000'
